language: python
install:
  - pip install -r requirements.txt
before_script:
  - npm install karma
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - python ./tests.py
  - npm test